### ISSUE TITLE
Allow elm-format to run even if there are syntax errors

### ISSUE THREAD

**Issue by Herteby** [klazuka/intellij-elm#341] opened 2019-03-05 11:37 UTC
Sloppily indented parenthesis around a case expression is invalid syntax according to the plugin, but valid according to the compiler:
```Elm
test maybe =
    String.fromInt
        (case maybe of
            Just _ ->
                1

            Nothing ->
                2
            )
```
What's annoying is that this blocks elm-format from fixing it.

Also, I think it'd be good if the plugin would attempt to run elm-format even if there's a syntax error, because some errors can actually be fixed by elm-format.

Invalid indentation, but elm-format fixes it:
```Elm
type alias Test =
{foo : String}
```
Elm-format automatically replaces `:` with `=`
```Elm
test = {foo:"foo"}
```

**Comment by klazuka** [comment] 2019-03-05 17:43
The first issue is a dupe of #22, which I have ignored for too long. I'll prioritize fixing it.

The 2nd and 3rd are both treated as syntax errors by the compiler.

I'm going to rename this issue so that it emphasizes the part about letting elm-format run even if there are syntax errors.

**Comment by klazuka** [comment] 2019-03-05 17:45
The main reluctance I had to allowing elm-format to run when there are syntax errors is that we didn't have a good way to show error output to the user. So that should be looked into before removing the guard.

**Comment by cmditch** [comment] 2019-03-18 19:04
Adding a vote in here too, also a fan of elm-format swapping `:` with `=` and vice versa. 

Thanks for the great plugin.

**Comment by Herteby** [comment] 2019-03-19 15:55
When I was using VSCode, elm-format would just fail silently if there was a syntax error, and I never found it confusing. Maybe you could just show a popup like "Formatting failed: code contains syntax errors".
I don't know how good the elm-format error messages are anyway.

**Comment by klazuka** [comment] 2019-03-19 17:23
@Herteby agreed. I'll do the quick fix right now. I don't think there's much we can do with nice error output since we can't get the `--report=json` data passed through from the Elm compiler to elm-format.

**Closed** 2019-03-19 18:23 UTC
