### ISSUE TITLE
SSCCE of contracdiction between linter and compiler

### ISSUE THREAD

**Issue by francescortiz** [klazuka/intellij-elm#550] opened 2019-11-18 13:35 UTC
I created an SSCCE of a case in which intellij-elm linter contradicts elm compiler:

https://github.com/francescortiz/intellij-elm-sscce

![image](https://user-images.githubusercontent.com/655264/69056468-5466d000-0a10-11ea-93a2-5534fff6d785.png)

The linter wants the return type of the view function to be `Html (Msg {})) ` while it only compiles if the return type of the view function is `Html (Msg (TypeA {}))`.

**Comment by ajalt** [comment] 2019-11-18 18:32
Thanks for the SSCCE! This is a duplicate of #482, which we chose not to fix. Using a type alias as a variant type argument can cause the elm compiler to remove fields from a record type, which shouldn't be possible.

**Closed** 2019-11-21 10:32 UTC
Labels: duplicate
