### ISSUE TITLE
Application package dependencies versions are not resolved correctly

### ISSUE THREAD

**Issue by vtsatskin** [klazuka/intellij-elm#681] opened 2020-08-14 20:31 UTC
When attempting to load the project found in [this example repo](https://github.com/vtsatskin/intellij-elm-package-bug), intellij-elm shows the following error:

<img width="456" alt="Screen Shot 2020-08-14 at 4 09 42 PM" src="https://user-images.githubusercontent.com/1301625/90288794-98282200-de48-11ea-9189-b7420bee2ce0.png">

`elm make` succeeds on this project, despite the error reported by intellij-elm. I've also tried loading this project in VS Code with the elm plugin and it also worked.

Looking closely at the error message, it shows that **elm-lang**/html could not be loaded, which is odd because we would expect **elm**/html to be loaded instead, based on the project's `elm.json`. After doing some debugging on the plugin itself, I've found the issue lies in how package versions are resolved within the plugin. `kalutheo/elm-ui-explorer v8.0.0` relies on `1602/elm-feather`, which is specified by the constraint `1.0.0 <= v < 2.3.5`. So in the following code, the earliest possible version number is used (1.0.0) instead of the version being used by the application (2.3.4) as specified in the `elm.json`. 

https://github.com/klazuka/intellij-elm/blob/d37b8edce008fad409002e170cfb34d9b0295f10/src/main/kotlin/org/elm/workspace/ElmProject.kt#L260

In this specific case, we could change the `min()` to `max()` and resolve the issue. However, choosing neither the minimum or maximum version would be correct in this example because the exact version specified by the project's `elm.json` should be used as it could be any version within the constraint.

At some point in the `1602/elm-feather`'s history the package names changed which caused this issue. While the issue could be resolved by constraining the versions of `1602/elm-feather` used by `kalutheo/elm-ui-explorer`, this still doesn't address the root of the issue where the wrong version of the root project's indirect dependencies were used.

**Comment by klazuka** [comment] 2020-08-15 14:56
My package resolution code has always been a hack. Although I thought it just affected package projects, not applications (where the elm.json has the version of everything).

Last week I started working on a proper implementation for the package case. It will brute-force solve the dependencies in the same way that the Elm compiler does it instead of doing dumb things like taking the `min()`.

I will wrap that up soon, and I will take another look at the “application” case, as this really surprises me that it’s not doing the right thing here.

Thanks for looking into this. And sorry for the trouble.

**Comment by klazuka** [comment] 2020-08-16 16:14
Yep, there's a major bug here even in the "application" case. I don't know what I was thinking when I wrote this code 😄 . The problem is that as it descends to build up the package tree, it ignores the top-level information about the actual version of direct and indirect dependencies.

I'm working on a fix for this as well as the tricker case where you attach a package at the top-level and we have to solve the dependency constraints.

**Comment by vtsatskin** [comment] 2020-08-17 14:18
@klazuka thanks so much for looking into this so quickly. Your analysis makes sense and I think the plan of action will solve the issue. I look forward to the fix when it's ready!

**Closed** 2020-08-17 19:39 UTC
