### ISSUE TITLE
IntelliJ 2021.2 support

### ISSUE THREAD

**Issue by avh4** [klazuka/intellij-elm#763] opened 2021-07-28 01:32 UTC
IntelliJ 2021.2 was released yesterday (2021-07-26), which starts the 212 series of builds [[changelog]](https://confluence.jetbrains.com/display/IDEADEV/IntelliJ+IDEA+2021.2+%28212.4746.92+build%29+Release+Notes?_gl=1*70jmz0*_ga*MTY5NTA3ODQ2Ny4xNjI3NDE5NDU3*_ga_V0XZL7QHEB*MTYyNzQzNTcxMC4yLjAuMTYyNzQzNTcxMS4w) [[version list]](https://www.jetbrains.com/idea/download/other.html).  The current version of the Elm plugin is disabled and cannot be re-enabled upon installing the new IntelliJ version.

For reference, the update for the previous 2021.1 is documented here: https://github.com/klazuka/intellij-elm/issues/743

**Comment by mickeyvip** [comment] 2021-07-28 12:41
I am not proficient with IntelliJ plugins, but I have a question:

Is there a reason the plugin version is tightly coupled to IntelliJ's minor version?

I mean, is there a chance that the plugin that works well in IntelliJ `2021.1` will not work in `2021.2`, `2021.3`, `2021.4`, ...?

Thank you

**Comment by yonigibbs** [comment] 2021-07-28 14:10
@mickeyvip, I think you're probably right. If it works on 2021.1 it will _probably_ work on 2021.2. The limitation is enforced [here](https://github.com/klazuka/intellij-elm/blob/master/src/main/resources/META-INF/plugin.xml#L334). It's possible that simply incrementing this value from to 211 to 212 will resolve the issue. However there are a few other issues with the codebase which are currently preventing it from being built. This is caused by the fact that [jcenter and bintray have been retired](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), and the code currently still refers to some dependencies from these artefact repos. @arian has opened PR #764 to try to get round these issues, and add support for IntelliJ 2021.2 at the same time.

**Comment by drathier** [comment] 2021-08-08 13:57
The last time this was fixed it wasn't that much work, so that's good new :) https://github.com/klazuka/intellij-elm/commit/d1d2b7caa75fc334011142a3ab491913c34eec2c

**Comment by dpinn** [comment] 2021-08-10 03:52
please, please, Please, PLEASE! (with cherries on top)

**Comment by Erudition** [comment] 2021-08-17 14:11
Is it worth trying to downgrade IDEa somehow? 
I only use it for Elm development (since this plugin is so good). It auto-updated with Snap, disabling Elm (any way to ask it to hold back based on plugin support?) and now I can't really do anything.
 I'm sure it could cause some issues to just switch to an older version, so I'm curious what you folks are doing about this

**Comment by Birowsky** [comment] 2021-08-17 14:20
@Erudition I just installed the older version. Had no issues at all.

**Comment by avh4** [comment] 2021-08-17 16:38
FYI, the way to get an old version with snap on Linux is:

```sh
snap refresh intellij-idea-community --channel=2021.1/stable --classic
```

(cc @Erudition)

**Comment by seunje** [comment] 2021-08-18 05:40
You can also use this https://www.jetbrains.com/toolbox-app/ to install & run different IntelliJ versions

**Comment by boxed** [comment] 2021-08-24 07:14
Can the build number limit be removed this time maybe? Seems better to YOLO it and hope it doesn't break instead of guaranteeing is breaks every release?

**Comment by tanhp1506** [comment] 2021-08-25 16:56
Hope the new release for supporting 2021.2 soon. I'll use the old version at the moment. 🙏🙏🙏

**Comment by guspower** [comment] 2021-08-30 13:48
fwiw I got the previous version of the plugin working with Intellij `2021.2.1`
(at least it recognises and loads the plugin, I've edited some elm files and the code hinting worked)

steps to reproduce:
1. Visit the plugins directory. For me this was `~/.local/share/JetBrains/IntelliJIdea2021.2`
2. Update the `plugin.xml` in `intellij-elm/lib/intellij-elm-4.4.0.jar`
    - navigate to the library: `cd intellij-elm/lib`
    - extract the plugin manifest: `unzip intellij-elm-4.4.0.jar META-INF/plugin.xml`
    - edit the plugin manifest: edit `META-INF/plugin.xml` line `326` so that the `until-build` tag specifies a later version, e.g. `until-build="213.*"/>`
    - update the plugin manifest: `zip -u intellij-elm-4.4.0.jar META-INF/plugin.xml`
3. Restart Intellij

**Comment by boxed** [comment] 2021-09-01 08:27
I just opened a PR to change this. Seems like a slam dunk. A merge and then a release should be everything that is needed.

**Comment by yonigibbs** [comment] 2021-09-01 08:52
@boxed, unfortunately I don't think that will work. I tried that very thing as well: #765. You're right that this is the solution to get it working with the latest version of IntelliJ. The problem is that, unrelated to the version of IntelliJ, the current code isn't able to build, because it uses dependencies from some artefact repos that are now retired :-( That's the PR that @arian is working on: #764.

**Comment by boxed** [comment] 2021-09-01 08:55
@yonigibbs That sounds like a totally different issue though. I think your PR should have been merged. I'll leave mine up because this seems to be the solution to the issue discussed here.

**Comment by yonigibbs** [comment] 2021-09-01 09:01
Yeah, agreed, the issues are not directly related. But unfortunately one is a blocker to the other: because the code won't build, the CI builds fail, so the PR can't be merged. (Unless of course @klazuka has set it up to allow merges even when the CI build fails.) But either way, even if it's merged, because it won't build, it won't be possible to build a new version to release.

**Comment by klazuka** [comment] 2021-09-20 14:46
Sorry. I've been out of Elm-land for a while now, and I get so many PRs at work that I just can't bring myself to spend more time in Github issues/PRs.

I just made [a release](https://github.com/klazuka/intellij-elm/releases/tag/v4.4.1) that removes the upper-bound on the IntelliJ version. The purpose of the upper-bound was to ensure that future breaking changes in IntelliJ don't break the Elm plugin. But I just don't have the time (nor the inclination) to keep up with Jetbrains releases any more.

The new version of the plugin should appear in the Jetbrains plugin repo in the next day or two.

**Closed by klazuka** 2021-09-20 14:46 UTC

**Comment by simonh1000** [comment] 2021-09-20 15:15
this sounds like an invitation to fork this code for the future?

**Comment by klazuka** [comment] 2021-09-20 15:19
That's fine with me. I don't see myself doing any further work on this plugin other than (infrequent) maintenance.

**Comment by boxed** [comment] 2021-09-20 18:33
@klazuka sould you be open to add a contributor to the repo? I'm not volenteering, just pointing out that forks have a tendency to be hard to find and make everything very bad.

**Comment by klazuka** [comment] 2021-09-20 18:34
Yep. That would be fine.

**Comment by billwanjohi** [comment] 2021-11-05 14:13
> would you be open to add a contributor to the repo

@klazuka unless you have an ongoing relationship with the new contributor, I would recommend against this course.

Since this repository and the published plugin are associated with your name (rather than an organization that you could publicly pass on to someone else's stewardship), any malice or negligence by someone that you merely add to your accounts would be backed by (and in turn influence) your reputation.

Recommending that users check out a new alternative (with or without an endorsement) does create some work for them, but it's work that they should be doing, to decide whether they trust the new developers.

**Comment by billwanjohi** [comment] 2021-11-05 14:41
An (admittedly extreme) example of what can go wrong played out in the NPM ecosystem a few years ago: https://www.theregister.com/2018/11/26/npm_repo_bitcoin_stealer/

**Comment by boxed** [comment] 2021-11-05 17:58
@billwanjohi this is a risk in proportion to the potential gains. In this case the gains are pretty insignificant for an attack.
