### ISSUE TITLE
Usage highlight incorrectly reporting unused

### ISSUE THREAD

**Issue by mordrax** [klazuka/intellij-elm#294] opened 2019-02-18 03:22 UTC
![image](https://user-images.githubusercontent.com/4709169/52925910-941c6080-3387-11e9-9ea2-5340aa8604d2.png)

`favouritesSection` does not auto complete when I add it to the list for `Menu.init [ ... ]` and it shows up as being unused.

I can make it show up as used by reordering some variables but not by adding a new line and forcing it to recompile on save.

Happens on 2.2.2 and 2.2.4

**Comment by klazuka** [comment] 2019-02-18 04:13
@mordrax are there any parse errors in the function involving this code? 

I wasn't able to reproduce based on the fragment shown. Can you post a larger sample (or email me the file privately)?

So "Find Usages" is working correctly, but code completion and the "unused symbol" feature are both broken in this case?

**Comment by opvasger** [comment] 2019-03-01 22:06
I think I've encountered the same issue - this example is based on [this repo](https://github.com/opvasger/elm-dev-tools) if you want to reproduce the error.
![image](https://user-images.githubusercontent.com/6593354/53668893-8fa05380-3c75-11e9-95fe-abe50f9b0c77.png)

The `sandbox` function is used in exactly the same way as the other functions here, yet it is the only one that shows up as unused.

When I right-click to *find usages* for `sandbox`, IntelliJ reports 2 usages (which is also true for all the other visible functions):
- the type-annotation above its definition
- the module-definition where it is exposed

**Comment by klazuka** [comment] 2019-03-01 22:39
@opvasger your issue is different. The unused symbol inspection _excludes_ type annotations and `exposing` list references as they are not "true" usages. In fact, if you toggle the "Show import statements" button in the "Find Usages" window, those usages will be hidden (and this is how I always use it).

As for why `sandbox` is marked as unused but, say, `element` is not, it's most likely due to a performance optimization where we trade-off false negatives (something that is truly unused but we fail to mark it as unused) in order to keep an upper-bound on performance. I described it a little in #319. That issue helped me realize that there was an opportunity to reduce the false negatives for function parameters (which was since been fixed), but I still need to do a little more tweaking to handle cases like this (function name) better.

--- 

@mordrax I'm going to close this issue, but feel free to re-open it if you can provide more details or a repro case.

**Closed by klazuka** 2019-03-01 22:39 UTC
