### ISSUE TITLE
Performance on Windows

### ISSUE THREAD

**Issue by jorgengranseth** [klazuka/intellij-elm#94] opened 2018-10-02 11:21 UTC
It seems like the plugin has performance issues on Windows.

I tried upgrading to the latest version of IntelliJ and played around with older versions of the plugin, which seemed to solve the problem also on the last version (3.3.0), but a day later I'm back to several seconds lag while typing. Navigation (in vim-mode) works as usual without lag, so it only seems to be a problem while the plugin is looking for autocomplete data (and seems more laggy in bigger projects).

Do you have any idea what may cause this or things I can try to fix it? Never had the issue with the old plugin on Windows, but obviously this one is desirable for all projects and necessary on 0.19 projects.

**Comment by klazuka** [comment] 2018-10-02 13:01
I develop on a Mac, so there very well could be a performance problem that I'm not aware of. @jorgengranseth how big is your Elm project? 

What flavor of IntelliJ are you using and what version? 

Can you reproduce the problem with [this example project](https://github.com/rtfeldman/elm-spa-example)?

**Comment by jorgengranseth** [comment] 2018-10-02 19:27
The one I'm working on right now is around 3300 LOC, so smaller than `elm-spa-example` (~5800 LOC). I get the same lag (on Windows) with that project.

I'm on IntelliJ IDEA 2018.2.4 (Ultimate Edition) built on September 18, but was using 2017.3.x before that (with the same issue).

**Comment by klazuka** [comment] 2018-10-03 13:48
I tried reproducing the issue in my Windows 10 VM using `elm-spa-example`, but everything was fine, both for Elm 0.18 and 0.19. Would you mind doing 2 things for me:

1. Go to File -> Settings -> Appearance -> Window Options and enable the checkbox for "Show Memory Indicator". This will show memory usage in the bottom-right of the IntelliJ window.
2. Go to Help -> Compress Logs and Show in Explorer. Then email me that zip file (klazuka at gmail.com).

**Comment by klazuka** [comment] 2018-10-04 23:11
Jorgen is still having a problem, and he has provided me with a CPU trace. But the investigation is at a standstill due to vacation. He's running Windows 7 and will upgrade to Windows 10 to see if that's any better. I'm going to close this now. If anyone is having similar problems, please feel free to re-open this issue and send me a CPU trace by following [these instructions](https://intellij-support.jetbrains.com/hc/en-us/articles/207241235-Reporting-performance-problems)

**Closed by klazuka** 2018-10-04 23:11 UTC
Labels: question
