### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by jorgengranseth** [klazuka/intellij-elm#624] opened 2020-03-10 09:37 UTC
Is there a way to use the plugin with a Dockerized Elm or plans to support this use case? I have started a container (`elm`) with `docker-compose` so the following works:
```
docker-compose run elm --version
0.19.1
```
However I don't have a path to the binary.

The plugin doesn't complain if I fill in `docker-compose run elm` for the compiler, but it also doesn't work.

**Comment by klazuka** [comment] 2020-03-12 15:18
I don't use Docker, but I would be willing to support it if you can figure out what's wrong.

Maybe the problem is that you are running IntelliJ in an environment where `docker-compose` is not on your path? Does it work if you use an absolute path?

**Comment by ajalt** [comment] 2020-03-12 15:57
I bet it's because of the spaces in the name; we're probably trying to run a binary named `docker-compose run elm` rather than a command named `docker-compose` with arguments `run elm --version`

Clikt had a similar issue: https://github.com/ajalt/clikt/issues/104

**Comment by jorgengranseth** [comment] 2020-03-13 13:57
I haven't used Docker much but it seems awfully convenient to handle global installs like Elm wants to be. This plugin is more important to my Elm workflow though. 👍

`docker-compose` is definitely on the path. In fact, if I leave `docker-compose` in the compiler field the plugin prints the version of `docker-compose`. So @ajalt's reasoning seems likely to be correct.

**Comment by OktarinTentakel** [comment] 2020-07-31 10:04
Any news on this? Can't find a way to reference elm inside a docker container either ...

**Comment by klazuka** [comment] 2020-07-31 14:57
It may be that there's an argument parsing issue, but I think that even if we got past that, there would be a deeper problem which is that the paths to the files in the IDE would be different than the paths inside the Docker container.

Suppose that my app source files are at `/Users/keith/dev/foo` and I bind-mount my app's source dir inside my Docker container as `/app`, how can the IDE map between the paths? For instance, the IDE has `/Users/keith/dev/foo/Bar.elm` open, and we want to invoke the Elm compiler on that file. We would need to run something like `docker run myImage elm make /app/Bar.elm`. But in order to construct that path we would need additional configuration (or we would need to parse the `docker run` CLI command or read the Docker Compose yml).

Which is do-able, but then we also need to translate the paths every time we invoke an external tool via Docker. Unless there's a simpler way, I don't see myself working on this.

**Comment by OktarinTentakel** [comment] 2020-07-31 17:17
I got past the compiler problem by writing a bash script calling the elm compiler with docker compose and relaying all params, but after that the plugin searched (of course) for packages on the host machine and not inside the container.

After that, for the sake of testing elm, I did a local install, but for production I still would be interested if anyone got a running, integrated setup with jetbrains with compiler, syntax completion and auto-format. Normally we do not install dev environments locally any more...

**Comment by klazuka** [comment] 2020-07-31 17:27
If you're on Linux then you can go down the rabbit hole and run IntelliJ from within the Docker container. I've never tried it, but there's this: https://github.com/rycus86/docker-intellij-idea

I'm going to close this out as I don't see a reasonable path forward.

**Closed by klazuka** 2020-07-31 17:27 UTC
