### ISSUE TITLE
Type checker false-positive: a let-in function w/ type annotation & type vars

### ISSUE THREAD

**Issue by romariolopezc** [klazuka/intellij-elm#408] opened 2019-05-25 15:32 UTC
![image](https://user-images.githubusercontent.com/6199588/58371567-0dbc7100-7ed8-11e9-80cd-579efcd5be28.png)

Running the elm compiler:
![image](https://user-images.githubusercontent.com/6199588/58371573-1614ac00-7ed8-11e9-8fc8-4aea5ea93b2d.png)

Running elm make:
```sh
romario ~/R/g/elm-frontend *develop λ elm make src/elm/Main.elm --output=elm.js
Success! Compiled 1 module.
```

**Comment by klazuka** [comment] 2019-05-25 16:14
This could be a false positive in our plugin's type checker, or maybe there's a problem with resolving the name/symbol. Where is `GotMemberEditorMsg` defined? Is it possibly defined in 2 different places? It could be that there's a bug in how I'm handling the imports.

**Comment by romariolopezc** [comment] 2019-05-25 16:20
`GotMemberEditorMsg` is defined in `Main.elm`

**Comment by klazuka** [comment] 2019-05-25 16:23
How is `viewAuthPage` defined? (including its type annotation)

Can you also paste your imports from the top of `Main.elm`?

**Comment by romariolopezc** [comment] 2019-05-25 16:24
```elm
        viewAuthPage : Page.Page -> (a -> Msg) -> { title : String, content : Html.Html a } -> Document Msg
        viewAuthPage currentPage toMsg config =
            let
                { title, body } =
                    Page.view (Session.viewer (toSession model)) currentPage (toPageState model) toMsg GotPageMsg config (toLanguage model)
            in
            { title = title
            , body = body
            }
```

```elm
import Api exposing (Cred)
import Browser exposing (Document)
import Browser.Navigation as Nav
import Html exposing (..)
import I18n
import Json.Decode as Decode exposing (Value)
import Page exposing (Page)
import Page.Blank as Blank
import Page.GettingStarted as GettingStarted
import Page.Home as Home
import Page.Login as Login
import Page.Member.Editor as MemberEditor
import Page.Members as Members
import Page.NotFound as NotFound
import Page.Profile as Profile
import Page.Register as Register
import Route exposing (Route)
import Session exposing (Session)
import Url exposing (Url)
import Viewer exposing (Viewer)
```

**Comment by romariolopezc** [comment] 2019-05-25 16:26
I just showed 1 but I have 3 failling with the same error:

![image](https://user-images.githubusercontent.com/6199588/58372204-dd78d080-7edf-11e9-855c-27a75cb5e473.png)

**Comment by klazuka** [comment] 2019-05-26 14:35
And are all 3 errors the same?

Maybe it's a caching problem? What happens if you type in the source file? Try adding a new function as well as changing the body of the function with the errors to make sure that the cache is cleared.

**Comment by romariolopezc** [comment] 2019-05-26 16:38
![image](https://user-images.githubusercontent.com/6199588/58384721-b3d8ab80-7faa-11e9-9502-abb108b68739.png)

![image](https://user-images.githubusercontent.com/6199588/58384725-b9ce8c80-7faa-11e9-9f4a-dacf65b22b28.png)

![image](https://user-images.githubusercontent.com/6199588/58384728-be934080-7faa-11e9-8170-2bfea4da43e5.png)

Yes all the same.

I deleted the code and added it, I re-indexed the project. No success, they still appear

**Comment by klazuka** [comment] 2019-05-28 18:41
I just released version 3.1.2 which has a bugfix related to curried functions. The new version should be available in the JetBrains plugin repo in the next 24-48 hours (or you can [download it from GitHub](https://github.com/klazuka/intellij-elm/releases/tag/v3.1.2) now).

Please let me know if this fixes the problem.

**Comment by romariolopezc** [comment] 2019-05-28 19:30
Fixed in 3.1.2 😃

**Comment by romariolopezc** [comment] 2019-05-29 14:26
Not fixed with the latest release, although I found where the error is.

If I delete the type definition for my function defined in `letin`, the error goes away.

Screenshots:
```elm
    let
        viewAuthPage : Page.Page -> (a -> Msg) -> { title : String, content : Html.Html a } -> Document Msg -- This type definition, if delete, the errors are gone
        viewAuthPage currentPage toMsg config =
            let
                { title, body } =
                    Page.view (Session.viewer (toSession model)) currentPage (toPageState model) toMsg GotPageMsg config (toLanguage model)
            in
            { title = title
            , body = body
            }
    in
```

The error:
![image](https://user-images.githubusercontent.com/6199588/58565077-b712a800-81f3-11e9-87af-aa3688928460.png)

**Comment by klazuka** [comment] 2019-05-29 18:14
@romariolopezc can you check to see what the Elm compiler thinks the type annotation for `viewAuthPage` *should* be? In 0.18 it used to print it out as a warning when un-annotated, but in 0.19 you have to fake it by just annotating it with something that is definitely wrong (e.g. `viewAuthPage : Int`).

**Comment by romariolopezc** [comment] 2019-05-29 20:02
I narrow it down to:

```elm
function : Msg
function =
    let
        mapper : (subMsg -> Msg) -> subMsg -> Msg -- If you delete this type definition, it won't show an error
        mapper map to =
            map to
    in
    mapper GotSubMsg One


type Msg
    = GotSubMsg SubMsg


type SubMsg
    = One
```

Copy this to a file in elm and you will see the linting error

**Comment by klazuka** [comment] 2019-05-29 20:28
@romariolopezc thanks!

@ajalt looks like a bug in type inference, both in version 3.1.1 and 3.1.2 (which was just released this morning).

**Comment by ajalt** [comment] 2019-05-29 22:47
Thanks for the report and the reproduction. This is a duplicate of #402. I'll post an update on that issue.

**Closed** 2019-06-01 20:05 UTC
Labels: bug
